# Generated by Django 5.0.6 on 2024-05-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_artist_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artist',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
    ]
