name: Build and push Docker image on tag push
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Autenticarse en el registry
        if: github.ref_type == 'tag'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
       
      - name: Construir imagen
        if: github.ref_type == 'tag'
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/amandafeijoo/BACKEND-UNIDAD_3/backend:${{ github.ref_name }}